// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: internal/contracts/agent.proto

package contracts

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AgentSeed struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Role          string                 `protobuf:"bytes,3,opt,name=role,proto3" json:"role,omitempty"`
	SystemPrompt  string                 `protobuf:"bytes,4,opt,name=system_prompt,json=systemPrompt,proto3" json:"system_prompt,omitempty"`
	Provider      string                 `protobuf:"bytes,5,opt,name=provider,proto3" json:"provider,omitempty"`
	Model         string                 `protobuf:"bytes,6,opt,name=model,proto3" json:"model,omitempty"`
	TeamId        string                 `protobuf:"bytes,7,opt,name=team_id,json=teamId,proto3" json:"team_id,omitempty"`
	IsLead        bool                   `protobuf:"varint,8,opt,name=is_lead,json=isLead,proto3" json:"is_lead,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentSeed) Reset() {
	*x = AgentSeed{}
	mi := &file_internal_contracts_agent_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentSeed) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentSeed) ProtoMessage() {}

func (x *AgentSeed) ProtoReflect() protoreflect.Message {
	mi := &file_internal_contracts_agent_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentSeed.ProtoReflect.Descriptor instead.
func (*AgentSeed) Descriptor() ([]byte, []int) {
	return file_internal_contracts_agent_proto_rawDescGZIP(), []int{0}
}

func (x *AgentSeed) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *AgentSeed) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AgentSeed) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *AgentSeed) GetSystemPrompt() string {
	if x != nil {
		return x.SystemPrompt
	}
	return ""
}

func (x *AgentSeed) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

func (x *AgentSeed) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *AgentSeed) GetTeamId() string {
	if x != nil {
		return x.TeamId
	}
	return ""
}

func (x *AgentSeed) GetIsLead() bool {
	if x != nil {
		return x.IsLead
	}
	return false
}

type ToolCall struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	ArgumentsJson string                 `protobuf:"bytes,3,opt,name=arguments_json,json=argumentsJson,proto3" json:"arguments_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ToolCall) Reset() {
	*x = ToolCall{}
	mi := &file_internal_contracts_agent_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToolCall) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToolCall) ProtoMessage() {}

func (x *ToolCall) ProtoReflect() protoreflect.Message {
	mi := &file_internal_contracts_agent_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToolCall.ProtoReflect.Descriptor instead.
func (*ToolCall) Descriptor() ([]byte, []int) {
	return file_internal_contracts_agent_proto_rawDescGZIP(), []int{1}
}

func (x *ToolCall) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ToolCall) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ToolCall) GetArgumentsJson() string {
	if x != nil {
		return x.ArgumentsJson
	}
	return ""
}

type ScriptedStep struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Content       string                 `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	ToolCalls     []*ToolCall            `protobuf:"bytes,3,rep,name=tool_calls,json=toolCalls,proto3" json:"tool_calls,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScriptedStep) Reset() {
	*x = ScriptedStep{}
	mi := &file_internal_contracts_agent_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScriptedStep) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScriptedStep) ProtoMessage() {}

func (x *ScriptedStep) ProtoReflect() protoreflect.Message {
	mi := &file_internal_contracts_agent_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScriptedStep.ProtoReflect.Descriptor instead.
func (*ScriptedStep) Descriptor() ([]byte, []int) {
	return file_internal_contracts_agent_proto_rawDescGZIP(), []int{2}
}

func (x *ScriptedStep) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *ScriptedStep) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *ScriptedStep) GetToolCalls() []*ToolCall {
	if x != nil {
		return x.ToolCalls
	}
	return nil
}

type ProviderConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Provider      string                 `protobuf:"bytes,1,opt,name=provider,proto3" json:"provider,omitempty"`
	Model         string                 `protobuf:"bytes,2,opt,name=model,proto3" json:"model,omitempty"`
	ApiKey        string                 `protobuf:"bytes,3,opt,name=api_key,json=apiKey,proto3" json:"api_key,omitempty"`
	BaseUrl       string                 `protobuf:"bytes,4,opt,name=base_url,json=baseUrl,proto3" json:"base_url,omitempty"`
	MaxTokens     int32                  `protobuf:"varint,5,opt,name=max_tokens,json=maxTokens,proto3" json:"max_tokens,omitempty"`
	Responses     []string               `protobuf:"bytes,6,rep,name=responses,proto3" json:"responses,omitempty"`
	TestMode      string                 `protobuf:"bytes,7,opt,name=test_mode,json=testMode,proto3" json:"test_mode,omitempty"`
	ScenarioFile  string                 `protobuf:"bytes,8,opt,name=scenario_file,json=scenarioFile,proto3" json:"scenario_file,omitempty"`
	Loop          bool                   `protobuf:"varint,9,opt,name=loop,proto3" json:"loop,omitempty"`
	Timeout       string                 `protobuf:"bytes,10,opt,name=timeout,proto3" json:"timeout,omitempty"`
	ContextWindow int32                  `protobuf:"varint,11,opt,name=context_window,json=contextWindow,proto3" json:"context_window,omitempty"`
	Steps         []*ScriptedStep        `protobuf:"bytes,12,rep,name=steps,proto3" json:"steps,omitempty"`
	Agents        []*AgentSeed           `protobuf:"bytes,13,rep,name=agents,proto3" json:"agents,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProviderConfig) Reset() {
	*x = ProviderConfig{}
	mi := &file_internal_contracts_agent_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProviderConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProviderConfig) ProtoMessage() {}

func (x *ProviderConfig) ProtoReflect() protoreflect.Message {
	mi := &file_internal_contracts_agent_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProviderConfig.ProtoReflect.Descriptor instead.
func (*ProviderConfig) Descriptor() ([]byte, []int) {
	return file_internal_contracts_agent_proto_rawDescGZIP(), []int{3}
}

func (x *ProviderConfig) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

func (x *ProviderConfig) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *ProviderConfig) GetApiKey() string {
	if x != nil {
		return x.ApiKey
	}
	return ""
}

func (x *ProviderConfig) GetBaseUrl() string {
	if x != nil {
		return x.BaseUrl
	}
	return ""
}

func (x *ProviderConfig) GetMaxTokens() int32 {
	if x != nil {
		return x.MaxTokens
	}
	return 0
}

func (x *ProviderConfig) GetResponses() []string {
	if x != nil {
		return x.Responses
	}
	return nil
}

func (x *ProviderConfig) GetTestMode() string {
	if x != nil {
		return x.TestMode
	}
	return ""
}

func (x *ProviderConfig) GetScenarioFile() string {
	if x != nil {
		return x.ScenarioFile
	}
	return ""
}

func (x *ProviderConfig) GetLoop() bool {
	if x != nil {
		return x.Loop
	}
	return false
}

func (x *ProviderConfig) GetTimeout() string {
	if x != nil {
		return x.Timeout
	}
	return ""
}

func (x *ProviderConfig) GetContextWindow() int32 {
	if x != nil {
		return x.ContextWindow
	}
	return 0
}

func (x *ProviderConfig) GetSteps() []*ScriptedStep {
	if x != nil {
		return x.Steps
	}
	return nil
}

func (x *ProviderConfig) GetAgents() []*AgentSeed {
	if x != nil {
		return x.Agents
	}
	return nil
}

type AgentExecuteConfig struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	MaxIterations   int32                  `protobuf:"varint,1,opt,name=max_iterations,json=maxIterations,proto3" json:"max_iterations,omitempty"`
	ProviderService string                 `protobuf:"bytes,2,opt,name=provider_service,json=providerService,proto3" json:"provider_service,omitempty"`
	ApprovalTimeout string                 `protobuf:"bytes,3,opt,name=approval_timeout,json=approvalTimeout,proto3" json:"approval_timeout,omitempty"`
	RequestTimeout  string                 `protobuf:"bytes,4,opt,name=request_timeout,json=requestTimeout,proto3" json:"request_timeout,omitempty"`
	LoopDetection   *LoopDetectionConfig   `protobuf:"bytes,5,opt,name=loop_detection,json=loopDetection,proto3" json:"loop_detection,omitempty"`
	Context         *AgentContextConfig    `protobuf:"bytes,6,opt,name=context,proto3" json:"context,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *AgentExecuteConfig) Reset() {
	*x = AgentExecuteConfig{}
	mi := &file_internal_contracts_agent_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentExecuteConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentExecuteConfig) ProtoMessage() {}

func (x *AgentExecuteConfig) ProtoReflect() protoreflect.Message {
	mi := &file_internal_contracts_agent_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentExecuteConfig.ProtoReflect.Descriptor instead.
func (*AgentExecuteConfig) Descriptor() ([]byte, []int) {
	return file_internal_contracts_agent_proto_rawDescGZIP(), []int{4}
}

func (x *AgentExecuteConfig) GetMaxIterations() int32 {
	if x != nil {
		return x.MaxIterations
	}
	return 0
}

func (x *AgentExecuteConfig) GetProviderService() string {
	if x != nil {
		return x.ProviderService
	}
	return ""
}

func (x *AgentExecuteConfig) GetApprovalTimeout() string {
	if x != nil {
		return x.ApprovalTimeout
	}
	return ""
}

func (x *AgentExecuteConfig) GetRequestTimeout() string {
	if x != nil {
		return x.RequestTimeout
	}
	return ""
}

func (x *AgentExecuteConfig) GetLoopDetection() *LoopDetectionConfig {
	if x != nil {
		return x.LoopDetection
	}
	return nil
}

func (x *AgentExecuteConfig) GetContext() *AgentContextConfig {
	if x != nil {
		return x.Context
	}
	return nil
}

type LoopDetectionConfig struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	MaxConsecutive int32                  `protobuf:"varint,1,opt,name=max_consecutive,json=maxConsecutive,proto3" json:"max_consecutive,omitempty"`
	MaxErrors      int32                  `protobuf:"varint,2,opt,name=max_errors,json=maxErrors,proto3" json:"max_errors,omitempty"`
	MaxAlternating int32                  `protobuf:"varint,3,opt,name=max_alternating,json=maxAlternating,proto3" json:"max_alternating,omitempty"`
	MaxNoProgress  int32                  `protobuf:"varint,4,opt,name=max_no_progress,json=maxNoProgress,proto3" json:"max_no_progress,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *LoopDetectionConfig) Reset() {
	*x = LoopDetectionConfig{}
	mi := &file_internal_contracts_agent_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoopDetectionConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoopDetectionConfig) ProtoMessage() {}

func (x *LoopDetectionConfig) ProtoReflect() protoreflect.Message {
	mi := &file_internal_contracts_agent_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoopDetectionConfig.ProtoReflect.Descriptor instead.
func (*LoopDetectionConfig) Descriptor() ([]byte, []int) {
	return file_internal_contracts_agent_proto_rawDescGZIP(), []int{5}
}

func (x *LoopDetectionConfig) GetMaxConsecutive() int32 {
	if x != nil {
		return x.MaxConsecutive
	}
	return 0
}

func (x *LoopDetectionConfig) GetMaxErrors() int32 {
	if x != nil {
		return x.MaxErrors
	}
	return 0
}

func (x *LoopDetectionConfig) GetMaxAlternating() int32 {
	if x != nil {
		return x.MaxAlternating
	}
	return 0
}

func (x *LoopDetectionConfig) GetMaxNoProgress() int32 {
	if x != nil {
		return x.MaxNoProgress
	}
	return 0
}

type AgentContextConfig struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	CompactionThreshold float64                `protobuf:"fixed64,1,opt,name=compaction_threshold,json=compactionThreshold,proto3" json:"compaction_threshold,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *AgentContextConfig) Reset() {
	*x = AgentContextConfig{}
	mi := &file_internal_contracts_agent_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentContextConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentContextConfig) ProtoMessage() {}

func (x *AgentContextConfig) ProtoReflect() protoreflect.Message {
	mi := &file_internal_contracts_agent_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentContextConfig.ProtoReflect.Descriptor instead.
func (*AgentContextConfig) Descriptor() ([]byte, []int) {
	return file_internal_contracts_agent_proto_rawDescGZIP(), []int{6}
}

func (x *AgentContextConfig) GetCompactionThreshold() float64 {
	if x != nil {
		return x.CompactionThreshold
	}
	return 0
}

type AgentExecuteInput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Provider      string                 `protobuf:"bytes,1,opt,name=provider,proto3" json:"provider,omitempty"`
	SystemPrompt  string                 `protobuf:"bytes,2,opt,name=system_prompt,json=systemPrompt,proto3" json:"system_prompt,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Task          string                 `protobuf:"bytes,4,opt,name=task,proto3" json:"task,omitempty"`
	AgentName     string                 `protobuf:"bytes,5,opt,name=agent_name,json=agentName,proto3" json:"agent_name,omitempty"`
	Name          string                 `protobuf:"bytes,6,opt,name=name,proto3" json:"name,omitempty"`
	AgentId       string                 `protobuf:"bytes,7,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	TaskId        string                 `protobuf:"bytes,8,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	Id            string                 `protobuf:"bytes,9,opt,name=id,proto3" json:"id,omitempty"`
	ProjectId     string                 `protobuf:"bytes,10,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentExecuteInput) Reset() {
	*x = AgentExecuteInput{}
	mi := &file_internal_contracts_agent_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentExecuteInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentExecuteInput) ProtoMessage() {}

func (x *AgentExecuteInput) ProtoReflect() protoreflect.Message {
	mi := &file_internal_contracts_agent_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentExecuteInput.ProtoReflect.Descriptor instead.
func (*AgentExecuteInput) Descriptor() ([]byte, []int) {
	return file_internal_contracts_agent_proto_rawDescGZIP(), []int{7}
}

func (x *AgentExecuteInput) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

func (x *AgentExecuteInput) GetSystemPrompt() string {
	if x != nil {
		return x.SystemPrompt
	}
	return ""
}

func (x *AgentExecuteInput) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *AgentExecuteInput) GetTask() string {
	if x != nil {
		return x.Task
	}
	return ""
}

func (x *AgentExecuteInput) GetAgentName() string {
	if x != nil {
		return x.AgentName
	}
	return ""
}

func (x *AgentExecuteInput) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AgentExecuteInput) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *AgentExecuteInput) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *AgentExecuteInput) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *AgentExecuteInput) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

type AgentExecuteOutput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        string                 `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	Iterations    int32                  `protobuf:"varint,3,opt,name=iterations,proto3" json:"iterations,omitempty"`
	Thinking      string                 `protobuf:"bytes,4,opt,name=thinking,proto3" json:"thinking,omitempty"`
	Error         string                 `protobuf:"bytes,100,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentExecuteOutput) Reset() {
	*x = AgentExecuteOutput{}
	mi := &file_internal_contracts_agent_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentExecuteOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentExecuteOutput) ProtoMessage() {}

func (x *AgentExecuteOutput) ProtoReflect() protoreflect.Message {
	mi := &file_internal_contracts_agent_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentExecuteOutput.ProtoReflect.Descriptor instead.
func (*AgentExecuteOutput) Descriptor() ([]byte, []int) {
	return file_internal_contracts_agent_proto_rawDescGZIP(), []int{8}
}

func (x *AgentExecuteOutput) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

func (x *AgentExecuteOutput) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *AgentExecuteOutput) GetIterations() int32 {
	if x != nil {
		return x.Iterations
	}
	return 0
}

func (x *AgentExecuteOutput) GetThinking() string {
	if x != nil {
		return x.Thinking
	}
	return ""
}

func (x *AgentExecuteOutput) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type ProviderTestConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Alias         string                 `protobuf:"bytes,1,opt,name=alias,proto3" json:"alias,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProviderTestConfig) Reset() {
	*x = ProviderTestConfig{}
	mi := &file_internal_contracts_agent_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProviderTestConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProviderTestConfig) ProtoMessage() {}

func (x *ProviderTestConfig) ProtoReflect() protoreflect.Message {
	mi := &file_internal_contracts_agent_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProviderTestConfig.ProtoReflect.Descriptor instead.
func (*ProviderTestConfig) Descriptor() ([]byte, []int) {
	return file_internal_contracts_agent_proto_rawDescGZIP(), []int{9}
}

func (x *ProviderTestConfig) GetAlias() string {
	if x != nil {
		return x.Alias
	}
	return ""
}

type ProviderTestInput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Alias         string                 `protobuf:"bytes,1,opt,name=alias,proto3" json:"alias,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProviderTestInput) Reset() {
	*x = ProviderTestInput{}
	mi := &file_internal_contracts_agent_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProviderTestInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProviderTestInput) ProtoMessage() {}

func (x *ProviderTestInput) ProtoReflect() protoreflect.Message {
	mi := &file_internal_contracts_agent_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProviderTestInput.ProtoReflect.Descriptor instead.
func (*ProviderTestInput) Descriptor() ([]byte, []int) {
	return file_internal_contracts_agent_proto_rawDescGZIP(), []int{10}
}

func (x *ProviderTestInput) GetAlias() string {
	if x != nil {
		return x.Alias
	}
	return ""
}

type ProviderTestOutput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	LatencyMs     int64                  `protobuf:"varint,3,opt,name=latency_ms,json=latencyMs,proto3" json:"latency_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProviderTestOutput) Reset() {
	*x = ProviderTestOutput{}
	mi := &file_internal_contracts_agent_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProviderTestOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProviderTestOutput) ProtoMessage() {}

func (x *ProviderTestOutput) ProtoReflect() protoreflect.Message {
	mi := &file_internal_contracts_agent_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProviderTestOutput.ProtoReflect.Descriptor instead.
func (*ProviderTestOutput) Descriptor() ([]byte, []int) {
	return file_internal_contracts_agent_proto_rawDescGZIP(), []int{11}
}

func (x *ProviderTestOutput) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ProviderTestOutput) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ProviderTestOutput) GetLatencyMs() int64 {
	if x != nil {
		return x.LatencyMs
	}
	return 0
}

type ProviderModelsConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProviderModelsConfig) Reset() {
	*x = ProviderModelsConfig{}
	mi := &file_internal_contracts_agent_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProviderModelsConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProviderModelsConfig) ProtoMessage() {}

func (x *ProviderModelsConfig) ProtoReflect() protoreflect.Message {
	mi := &file_internal_contracts_agent_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProviderModelsConfig.ProtoReflect.Descriptor instead.
func (*ProviderModelsConfig) Descriptor() ([]byte, []int) {
	return file_internal_contracts_agent_proto_rawDescGZIP(), []int{12}
}

type ProviderModelsInput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProviderType  string                 `protobuf:"bytes,1,opt,name=provider_type,json=providerType,proto3" json:"provider_type,omitempty"`
	ApiKey        string                 `protobuf:"bytes,2,opt,name=api_key,json=apiKey,proto3" json:"api_key,omitempty"`
	BaseUrl       string                 `protobuf:"bytes,3,opt,name=base_url,json=baseUrl,proto3" json:"base_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProviderModelsInput) Reset() {
	*x = ProviderModelsInput{}
	mi := &file_internal_contracts_agent_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProviderModelsInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProviderModelsInput) ProtoMessage() {}

func (x *ProviderModelsInput) ProtoReflect() protoreflect.Message {
	mi := &file_internal_contracts_agent_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProviderModelsInput.ProtoReflect.Descriptor instead.
func (*ProviderModelsInput) Descriptor() ([]byte, []int) {
	return file_internal_contracts_agent_proto_rawDescGZIP(), []int{13}
}

func (x *ProviderModelsInput) GetProviderType() string {
	if x != nil {
		return x.ProviderType
	}
	return ""
}

func (x *ProviderModelsInput) GetApiKey() string {
	if x != nil {
		return x.ApiKey
	}
	return ""
}

func (x *ProviderModelsInput) GetBaseUrl() string {
	if x != nil {
		return x.BaseUrl
	}
	return ""
}

type ProviderModel struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	ContextWindow int32                  `protobuf:"varint,3,opt,name=context_window,json=contextWindow,proto3" json:"context_window,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProviderModel) Reset() {
	*x = ProviderModel{}
	mi := &file_internal_contracts_agent_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProviderModel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProviderModel) ProtoMessage() {}

func (x *ProviderModel) ProtoReflect() protoreflect.Message {
	mi := &file_internal_contracts_agent_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProviderModel.ProtoReflect.Descriptor instead.
func (*ProviderModel) Descriptor() ([]byte, []int) {
	return file_internal_contracts_agent_proto_rawDescGZIP(), []int{14}
}

func (x *ProviderModel) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ProviderModel) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ProviderModel) GetContextWindow() int32 {
	if x != nil {
		return x.ContextWindow
	}
	return 0
}

type ProviderModelsOutput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Models        []*ProviderModel       `protobuf:"bytes,2,rep,name=models,proto3" json:"models,omitempty"`
	Error         string                 `protobuf:"bytes,100,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProviderModelsOutput) Reset() {
	*x = ProviderModelsOutput{}
	mi := &file_internal_contracts_agent_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProviderModelsOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProviderModelsOutput) ProtoMessage() {}

func (x *ProviderModelsOutput) ProtoReflect() protoreflect.Message {
	mi := &file_internal_contracts_agent_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProviderModelsOutput.ProtoReflect.Descriptor instead.
func (*ProviderModelsOutput) Descriptor() ([]byte, []int) {
	return file_internal_contracts_agent_proto_rawDescGZIP(), []int{15}
}

func (x *ProviderModelsOutput) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ProviderModelsOutput) GetModels() []*ProviderModel {
	if x != nil {
		return x.Models
	}
	return nil
}

func (x *ProviderModelsOutput) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type ModelPullConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Provider      string                 `protobuf:"bytes,1,opt,name=provider,proto3" json:"provider,omitempty"`
	Source        string                 `protobuf:"bytes,2,opt,name=source,proto3" json:"source,omitempty"`
	Model         string                 `protobuf:"bytes,3,opt,name=model,proto3" json:"model,omitempty"`
	File          string                 `protobuf:"bytes,4,opt,name=file,proto3" json:"file,omitempty"`
	OutputDir     string                 `protobuf:"bytes,5,opt,name=output_dir,json=outputDir,proto3" json:"output_dir,omitempty"`
	BaseUrl       string                 `protobuf:"bytes,6,opt,name=base_url,json=baseUrl,proto3" json:"base_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ModelPullConfig) Reset() {
	*x = ModelPullConfig{}
	mi := &file_internal_contracts_agent_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ModelPullConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModelPullConfig) ProtoMessage() {}

func (x *ModelPullConfig) ProtoReflect() protoreflect.Message {
	mi := &file_internal_contracts_agent_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModelPullConfig.ProtoReflect.Descriptor instead.
func (*ModelPullConfig) Descriptor() ([]byte, []int) {
	return file_internal_contracts_agent_proto_rawDescGZIP(), []int{16}
}

func (x *ModelPullConfig) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

func (x *ModelPullConfig) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *ModelPullConfig) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *ModelPullConfig) GetFile() string {
	if x != nil {
		return x.File
	}
	return ""
}

func (x *ModelPullConfig) GetOutputDir() string {
	if x != nil {
		return x.OutputDir
	}
	return ""
}

func (x *ModelPullConfig) GetBaseUrl() string {
	if x != nil {
		return x.BaseUrl
	}
	return ""
}

type ModelPullInput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ModelPullInput) Reset() {
	*x = ModelPullInput{}
	mi := &file_internal_contracts_agent_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ModelPullInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModelPullInput) ProtoMessage() {}

func (x *ModelPullInput) ProtoReflect() protoreflect.Message {
	mi := &file_internal_contracts_agent_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModelPullInput.ProtoReflect.Descriptor instead.
func (*ModelPullInput) Descriptor() ([]byte, []int) {
	return file_internal_contracts_agent_proto_rawDescGZIP(), []int{17}
}

type ModelPullOutput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	ModelPath     string                 `protobuf:"bytes,2,opt,name=model_path,json=modelPath,proto3" json:"model_path,omitempty"`
	SizeBytes     int64                  `protobuf:"varint,3,opt,name=size_bytes,json=sizeBytes,proto3" json:"size_bytes,omitempty"`
	Error         string                 `protobuf:"bytes,100,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ModelPullOutput) Reset() {
	*x = ModelPullOutput{}
	mi := &file_internal_contracts_agent_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ModelPullOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModelPullOutput) ProtoMessage() {}

func (x *ModelPullOutput) ProtoReflect() protoreflect.Message {
	mi := &file_internal_contracts_agent_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModelPullOutput.ProtoReflect.Descriptor instead.
func (*ModelPullOutput) Descriptor() ([]byte, []int) {
	return file_internal_contracts_agent_proto_rawDescGZIP(), []int{18}
}

func (x *ModelPullOutput) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ModelPullOutput) GetModelPath() string {
	if x != nil {
		return x.ModelPath
	}
	return ""
}

func (x *ModelPullOutput) GetSizeBytes() int64 {
	if x != nil {
		return x.SizeBytes
	}
	return 0
}

func (x *ModelPullOutput) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_internal_contracts_agent_proto protoreflect.FileDescriptor

const file_internal_contracts_agent_proto_rawDesc = "" +
	"\n" +
	"\x1einternal/contracts/agent.proto\x12\x19workflow.plugins.agent.v1\"\xcc\x01\n" +
	"\tAgentSeed\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04role\x18\x03 \x01(\tR\x04role\x12#\n" +
	"\rsystem_prompt\x18\x04 \x01(\tR\fsystemPrompt\x12\x1a\n" +
	"\bprovider\x18\x05 \x01(\tR\bprovider\x12\x14\n" +
	"\x05model\x18\x06 \x01(\tR\x05model\x12\x17\n" +
	"\ateam_id\x18\a \x01(\tR\x06teamId\x12\x17\n" +
	"\ais_lead\x18\b \x01(\bR\x06isLead\"U\n" +
	"\bToolCall\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12%\n" +
	"\x0earguments_json\x18\x03 \x01(\tR\rargumentsJson\"\x82\x01\n" +
	"\fScriptedStep\x12\x18\n" +
	"\acontent\x18\x01 \x01(\tR\acontent\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\x12B\n" +
	"\n" +
	"tool_calls\x18\x03 \x03(\v2#.workflow.plugins.agent.v1.ToolCallR\ttoolCalls\"\xc7\x03\n" +
	"\x0eProviderConfig\x12\x1a\n" +
	"\bprovider\x18\x01 \x01(\tR\bprovider\x12\x14\n" +
	"\x05model\x18\x02 \x01(\tR\x05model\x12\x17\n" +
	"\aapi_key\x18\x03 \x01(\tR\x06apiKey\x12\x19\n" +
	"\bbase_url\x18\x04 \x01(\tR\abaseUrl\x12\x1d\n" +
	"\n" +
	"max_tokens\x18\x05 \x01(\x05R\tmaxTokens\x12\x1c\n" +
	"\tresponses\x18\x06 \x03(\tR\tresponses\x12\x1b\n" +
	"\ttest_mode\x18\a \x01(\tR\btestMode\x12#\n" +
	"\rscenario_file\x18\b \x01(\tR\fscenarioFile\x12\x12\n" +
	"\x04loop\x18\t \x01(\bR\x04loop\x12\x18\n" +
	"\atimeout\x18\n" +
	" \x01(\tR\atimeout\x12%\n" +
	"\x0econtext_window\x18\v \x01(\x05R\rcontextWindow\x12=\n" +
	"\x05steps\x18\f \x03(\v2'.workflow.plugins.agent.v1.ScriptedStepR\x05steps\x12<\n" +
	"\x06agents\x18\r \x03(\v2$.workflow.plugins.agent.v1.AgentSeedR\x06agents\"\xda\x02\n" +
	"\x12AgentExecuteConfig\x12%\n" +
	"\x0emax_iterations\x18\x01 \x01(\x05R\rmaxIterations\x12)\n" +
	"\x10provider_service\x18\x02 \x01(\tR\x0fproviderService\x12)\n" +
	"\x10approval_timeout\x18\x03 \x01(\tR\x0fapprovalTimeout\x12'\n" +
	"\x0frequest_timeout\x18\x04 \x01(\tR\x0erequestTimeout\x12U\n" +
	"\x0eloop_detection\x18\x05 \x01(\v2..workflow.plugins.agent.v1.LoopDetectionConfigR\rloopDetection\x12G\n" +
	"\acontext\x18\x06 \x01(\v2-.workflow.plugins.agent.v1.AgentContextConfigR\acontext\"\xae\x01\n" +
	"\x13LoopDetectionConfig\x12'\n" +
	"\x0fmax_consecutive\x18\x01 \x01(\x05R\x0emaxConsecutive\x12\x1d\n" +
	"\n" +
	"max_errors\x18\x02 \x01(\x05R\tmaxErrors\x12'\n" +
	"\x0fmax_alternating\x18\x03 \x01(\x05R\x0emaxAlternating\x12&\n" +
	"\x0fmax_no_progress\x18\x04 \x01(\x05R\rmaxNoProgress\"G\n" +
	"\x12AgentContextConfig\x121\n" +
	"\x14compaction_threshold\x18\x01 \x01(\x01R\x13compactionThreshold\"\xa0\x02\n" +
	"\x11AgentExecuteInput\x12\x1a\n" +
	"\bprovider\x18\x01 \x01(\tR\bprovider\x12#\n" +
	"\rsystem_prompt\x18\x02 \x01(\tR\fsystemPrompt\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x12\n" +
	"\x04task\x18\x04 \x01(\tR\x04task\x12\x1d\n" +
	"\n" +
	"agent_name\x18\x05 \x01(\tR\tagentName\x12\x12\n" +
	"\x04name\x18\x06 \x01(\tR\x04name\x12\x19\n" +
	"\bagent_id\x18\a \x01(\tR\aagentId\x12\x17\n" +
	"\atask_id\x18\b \x01(\tR\x06taskId\x12\x0e\n" +
	"\x02id\x18\t \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"project_id\x18\n" +
	" \x01(\tR\tprojectId\"\x96\x01\n" +
	"\x12AgentExecuteOutput\x12\x16\n" +
	"\x06result\x18\x01 \x01(\tR\x06result\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x1e\n" +
	"\n" +
	"iterations\x18\x03 \x01(\x05R\n" +
	"iterations\x12\x1a\n" +
	"\bthinking\x18\x04 \x01(\tR\bthinking\x12\x14\n" +
	"\x05error\x18d \x01(\tR\x05error\"*\n" +
	"\x12ProviderTestConfig\x12\x14\n" +
	"\x05alias\x18\x01 \x01(\tR\x05alias\")\n" +
	"\x11ProviderTestInput\x12\x14\n" +
	"\x05alias\x18\x01 \x01(\tR\x05alias\"g\n" +
	"\x12ProviderTestOutput\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x1d\n" +
	"\n" +
	"latency_ms\x18\x03 \x01(\x03R\tlatencyMs\"\x16\n" +
	"\x14ProviderModelsConfig\"n\n" +
	"\x13ProviderModelsInput\x12#\n" +
	"\rprovider_type\x18\x01 \x01(\tR\fproviderType\x12\x17\n" +
	"\aapi_key\x18\x02 \x01(\tR\x06apiKey\x12\x19\n" +
	"\bbase_url\x18\x03 \x01(\tR\abaseUrl\"Z\n" +
	"\rProviderModel\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12%\n" +
	"\x0econtext_window\x18\x03 \x01(\x05R\rcontextWindow\"\x88\x01\n" +
	"\x14ProviderModelsOutput\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12@\n" +
	"\x06models\x18\x02 \x03(\v2(.workflow.plugins.agent.v1.ProviderModelR\x06models\x12\x14\n" +
	"\x05error\x18d \x01(\tR\x05error\"\xa9\x01\n" +
	"\x0fModelPullConfig\x12\x1a\n" +
	"\bprovider\x18\x01 \x01(\tR\bprovider\x12\x16\n" +
	"\x06source\x18\x02 \x01(\tR\x06source\x12\x14\n" +
	"\x05model\x18\x03 \x01(\tR\x05model\x12\x12\n" +
	"\x04file\x18\x04 \x01(\tR\x04file\x12\x1d\n" +
	"\n" +
	"output_dir\x18\x05 \x01(\tR\toutputDir\x12\x19\n" +
	"\bbase_url\x18\x06 \x01(\tR\abaseUrl\"\x10\n" +
	"\x0eModelPullInput\"}\n" +
	"\x0fModelPullOutput\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x1d\n" +
	"\n" +
	"model_path\x18\x02 \x01(\tR\tmodelPath\x12\x1d\n" +
	"\n" +
	"size_bytes\x18\x03 \x01(\x03R\tsizeBytes\x12\x14\n" +
	"\x05error\x18d \x01(\tR\x05errorBKZIgithub.com/GoCodeAlone/workflow-plugin-agent/internal/contracts;contractsb\x06proto3"

var (
	file_internal_contracts_agent_proto_rawDescOnce sync.Once
	file_internal_contracts_agent_proto_rawDescData []byte
)

func file_internal_contracts_agent_proto_rawDescGZIP() []byte {
	file_internal_contracts_agent_proto_rawDescOnce.Do(func() {
		file_internal_contracts_agent_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_contracts_agent_proto_rawDesc), len(file_internal_contracts_agent_proto_rawDesc)))
	})
	return file_internal_contracts_agent_proto_rawDescData
}

var file_internal_contracts_agent_proto_msgTypes = make([]protoimpl.MessageInfo, 19)
var file_internal_contracts_agent_proto_goTypes = []any{
	(*AgentSeed)(nil),            // 0: workflow.plugins.agent.v1.AgentSeed
	(*ToolCall)(nil),             // 1: workflow.plugins.agent.v1.ToolCall
	(*ScriptedStep)(nil),         // 2: workflow.plugins.agent.v1.ScriptedStep
	(*ProviderConfig)(nil),       // 3: workflow.plugins.agent.v1.ProviderConfig
	(*AgentExecuteConfig)(nil),   // 4: workflow.plugins.agent.v1.AgentExecuteConfig
	(*LoopDetectionConfig)(nil),  // 5: workflow.plugins.agent.v1.LoopDetectionConfig
	(*AgentContextConfig)(nil),   // 6: workflow.plugins.agent.v1.AgentContextConfig
	(*AgentExecuteInput)(nil),    // 7: workflow.plugins.agent.v1.AgentExecuteInput
	(*AgentExecuteOutput)(nil),   // 8: workflow.plugins.agent.v1.AgentExecuteOutput
	(*ProviderTestConfig)(nil),   // 9: workflow.plugins.agent.v1.ProviderTestConfig
	(*ProviderTestInput)(nil),    // 10: workflow.plugins.agent.v1.ProviderTestInput
	(*ProviderTestOutput)(nil),   // 11: workflow.plugins.agent.v1.ProviderTestOutput
	(*ProviderModelsConfig)(nil), // 12: workflow.plugins.agent.v1.ProviderModelsConfig
	(*ProviderModelsInput)(nil),  // 13: workflow.plugins.agent.v1.ProviderModelsInput
	(*ProviderModel)(nil),        // 14: workflow.plugins.agent.v1.ProviderModel
	(*ProviderModelsOutput)(nil), // 15: workflow.plugins.agent.v1.ProviderModelsOutput
	(*ModelPullConfig)(nil),      // 16: workflow.plugins.agent.v1.ModelPullConfig
	(*ModelPullInput)(nil),       // 17: workflow.plugins.agent.v1.ModelPullInput
	(*ModelPullOutput)(nil),      // 18: workflow.plugins.agent.v1.ModelPullOutput
}
var file_internal_contracts_agent_proto_depIdxs = []int32{
	1,  // 0: workflow.plugins.agent.v1.ScriptedStep.tool_calls:type_name -> workflow.plugins.agent.v1.ToolCall
	2,  // 1: workflow.plugins.agent.v1.ProviderConfig.steps:type_name -> workflow.plugins.agent.v1.ScriptedStep
	0,  // 2: workflow.plugins.agent.v1.ProviderConfig.agents:type_name -> workflow.plugins.agent.v1.AgentSeed
	5,  // 3: workflow.plugins.agent.v1.AgentExecuteConfig.loop_detection:type_name -> workflow.plugins.agent.v1.LoopDetectionConfig
	6,  // 4: workflow.plugins.agent.v1.AgentExecuteConfig.context:type_name -> workflow.plugins.agent.v1.AgentContextConfig
	14, // 5: workflow.plugins.agent.v1.ProviderModelsOutput.models:type_name -> workflow.plugins.agent.v1.ProviderModel
	6,  // [6:6] is the sub-list for method output_type
	6,  // [6:6] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_internal_contracts_agent_proto_init() }
func file_internal_contracts_agent_proto_init() {
	if File_internal_contracts_agent_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_contracts_agent_proto_rawDesc), len(file_internal_contracts_agent_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   19,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_internal_contracts_agent_proto_goTypes,
		DependencyIndexes: file_internal_contracts_agent_proto_depIdxs,
		MessageInfos:      file_internal_contracts_agent_proto_msgTypes,
	}.Build()
	File_internal_contracts_agent_proto = out.File
	file_internal_contracts_agent_proto_goTypes = nil
	file_internal_contracts_agent_proto_depIdxs = nil
}
