// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.0
// source: internal/contracts/orchestrator.proto

package contracts

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LspDiagnoseConfig struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// content_key overrides the pc.Current key read for YAML content
	// (default: "yaml"; the step also falls back to "content").
	ContentKey    string `protobuf:"bytes,1,opt,name=content_key,json=contentKey,proto3" json:"content_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LspDiagnoseConfig) Reset() {
	*x = LspDiagnoseConfig{}
	mi := &file_internal_contracts_orchestrator_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LspDiagnoseConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LspDiagnoseConfig) ProtoMessage() {}

func (x *LspDiagnoseConfig) ProtoReflect() protoreflect.Message {
	mi := &file_internal_contracts_orchestrator_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LspDiagnoseConfig.ProtoReflect.Descriptor instead.
func (*LspDiagnoseConfig) Descriptor() ([]byte, []int) {
	return file_internal_contracts_orchestrator_proto_rawDescGZIP(), []int{0}
}

func (x *LspDiagnoseConfig) GetContentKey() string {
	if x != nil {
		return x.ContentKey
	}
	return ""
}

type LspDiagnoseInput struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// yaml is the primary YAML content to diagnose.
	Yaml string `protobuf:"bytes,1,opt,name=yaml,proto3" json:"yaml,omitempty"`
	// content is the fallback YAML content key.
	Content       string `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LspDiagnoseInput) Reset() {
	*x = LspDiagnoseInput{}
	mi := &file_internal_contracts_orchestrator_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LspDiagnoseInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LspDiagnoseInput) ProtoMessage() {}

func (x *LspDiagnoseInput) ProtoReflect() protoreflect.Message {
	mi := &file_internal_contracts_orchestrator_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LspDiagnoseInput.ProtoReflect.Descriptor instead.
func (*LspDiagnoseInput) Descriptor() ([]byte, []int) {
	return file_internal_contracts_orchestrator_proto_rawDescGZIP(), []int{1}
}

func (x *LspDiagnoseInput) GetYaml() string {
	if x != nil {
		return x.Yaml
	}
	return ""
}

func (x *LspDiagnoseInput) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

type LspDiagnostic struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Severity      string                 `protobuf:"bytes,1,opt,name=severity,proto3" json:"severity,omitempty"` // "error", "warning", "info"
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Range         string                 `protobuf:"bytes,3,opt,name=range,proto3" json:"range,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LspDiagnostic) Reset() {
	*x = LspDiagnostic{}
	mi := &file_internal_contracts_orchestrator_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LspDiagnostic) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LspDiagnostic) ProtoMessage() {}

func (x *LspDiagnostic) ProtoReflect() protoreflect.Message {
	mi := &file_internal_contracts_orchestrator_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LspDiagnostic.ProtoReflect.Descriptor instead.
func (*LspDiagnostic) Descriptor() ([]byte, []int) {
	return file_internal_contracts_orchestrator_proto_rawDescGZIP(), []int{2}
}

func (x *LspDiagnostic) GetSeverity() string {
	if x != nil {
		return x.Severity
	}
	return ""
}

func (x *LspDiagnostic) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *LspDiagnostic) GetRange() string {
	if x != nil {
		return x.Range
	}
	return ""
}

type LspDiagnoseOutput struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	Diagnostics []*LspDiagnostic       `protobuf:"bytes,1,rep,name=diagnostics,proto3" json:"diagnostics,omitempty"`
	Count       int32                  `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	HasErrors   bool                   `protobuf:"varint,3,opt,name=has_errors,json=hasErrors,proto3" json:"has_errors,omitempty"`
	// warning is set when YAML is empty or the LSP provider is unavailable
	// (graceful-degradation path; not an error).
	Warning       string `protobuf:"bytes,100,opt,name=warning,proto3" json:"warning,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LspDiagnoseOutput) Reset() {
	*x = LspDiagnoseOutput{}
	mi := &file_internal_contracts_orchestrator_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LspDiagnoseOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LspDiagnoseOutput) ProtoMessage() {}

func (x *LspDiagnoseOutput) ProtoReflect() protoreflect.Message {
	mi := &file_internal_contracts_orchestrator_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LspDiagnoseOutput.ProtoReflect.Descriptor instead.
func (*LspDiagnoseOutput) Descriptor() ([]byte, []int) {
	return file_internal_contracts_orchestrator_proto_rawDescGZIP(), []int{3}
}

func (x *LspDiagnoseOutput) GetDiagnostics() []*LspDiagnostic {
	if x != nil {
		return x.Diagnostics
	}
	return nil
}

func (x *LspDiagnoseOutput) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *LspDiagnoseOutput) GetHasErrors() bool {
	if x != nil {
		return x.HasErrors
	}
	return false
}

func (x *LspDiagnoseOutput) GetWarning() string {
	if x != nil {
		return x.Warning
	}
	return ""
}

type SelfImproveValidateConfig struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// proposed_key overrides the pc.Current key holding the proposed YAML
	// (default: "proposed_yaml").
	ProposedKey string `protobuf:"bytes,1,opt,name=proposed_key,json=proposedKey,proto3" json:"proposed_key,omitempty"`
	// current_key overrides the pc.Current key holding the current YAML
	// (default: "current_yaml").
	CurrentKey string `protobuf:"bytes,2,opt,name=current_key,json=currentKey,proto3" json:"current_key,omitempty"`
	// proposed_yaml_file, when set, reads proposed YAML from this path instead of
	// proposed_key.
	ProposedYamlFile string `protobuf:"bytes,3,opt,name=proposed_yaml_file,json=proposedYamlFile,proto3" json:"proposed_yaml_file,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *SelfImproveValidateConfig) Reset() {
	*x = SelfImproveValidateConfig{}
	mi := &file_internal_contracts_orchestrator_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SelfImproveValidateConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SelfImproveValidateConfig) ProtoMessage() {}

func (x *SelfImproveValidateConfig) ProtoReflect() protoreflect.Message {
	mi := &file_internal_contracts_orchestrator_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SelfImproveValidateConfig.ProtoReflect.Descriptor instead.
func (*SelfImproveValidateConfig) Descriptor() ([]byte, []int) {
	return file_internal_contracts_orchestrator_proto_rawDescGZIP(), []int{4}
}

func (x *SelfImproveValidateConfig) GetProposedKey() string {
	if x != nil {
		return x.ProposedKey
	}
	return ""
}

func (x *SelfImproveValidateConfig) GetCurrentKey() string {
	if x != nil {
		return x.CurrentKey
	}
	return ""
}

func (x *SelfImproveValidateConfig) GetProposedYamlFile() string {
	if x != nil {
		return x.ProposedYamlFile
	}
	return ""
}

type SelfImproveValidateInput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProposedYaml  string                 `protobuf:"bytes,1,opt,name=proposed_yaml,json=proposedYaml,proto3" json:"proposed_yaml,omitempty"`
	CurrentYaml   string                 `protobuf:"bytes,2,opt,name=current_yaml,json=currentYaml,proto3" json:"current_yaml,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SelfImproveValidateInput) Reset() {
	*x = SelfImproveValidateInput{}
	mi := &file_internal_contracts_orchestrator_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SelfImproveValidateInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SelfImproveValidateInput) ProtoMessage() {}

func (x *SelfImproveValidateInput) ProtoReflect() protoreflect.Message {
	mi := &file_internal_contracts_orchestrator_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SelfImproveValidateInput.ProtoReflect.Descriptor instead.
func (*SelfImproveValidateInput) Descriptor() ([]byte, []int) {
	return file_internal_contracts_orchestrator_proto_rawDescGZIP(), []int{5}
}

func (x *SelfImproveValidateInput) GetProposedYaml() string {
	if x != nil {
		return x.ProposedYaml
	}
	return ""
}

func (x *SelfImproveValidateInput) GetCurrentYaml() string {
	if x != nil {
		return x.CurrentYaml
	}
	return ""
}

type SelfImproveValidateOutput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Valid         bool                   `protobuf:"varint,1,opt,name=valid,proto3" json:"valid,omitempty"`
	Errors        []string               `protobuf:"bytes,2,rep,name=errors,proto3" json:"errors,omitempty"`
	Warnings      []string               `protobuf:"bytes,3,rep,name=warnings,proto3" json:"warnings,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SelfImproveValidateOutput) Reset() {
	*x = SelfImproveValidateOutput{}
	mi := &file_internal_contracts_orchestrator_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SelfImproveValidateOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SelfImproveValidateOutput) ProtoMessage() {}

func (x *SelfImproveValidateOutput) ProtoReflect() protoreflect.Message {
	mi := &file_internal_contracts_orchestrator_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SelfImproveValidateOutput.ProtoReflect.Descriptor instead.
func (*SelfImproveValidateOutput) Descriptor() ([]byte, []int) {
	return file_internal_contracts_orchestrator_proto_rawDescGZIP(), []int{6}
}

func (x *SelfImproveValidateOutput) GetValid() bool {
	if x != nil {
		return x.Valid
	}
	return false
}

func (x *SelfImproveValidateOutput) GetErrors() []string {
	if x != nil {
		return x.Errors
	}
	return nil
}

func (x *SelfImproveValidateOutput) GetWarnings() []string {
	if x != nil {
		return x.Warnings
	}
	return nil
}

type SelfImproveDiffConfig struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	ProposedKey        string                 `protobuf:"bytes,1,opt,name=proposed_key,json=proposedKey,proto3" json:"proposed_key,omitempty"` // default: "proposed_yaml"
	CurrentKey         string                 `protobuf:"bytes,2,opt,name=current_key,json=currentKey,proto3" json:"current_key,omitempty"`    // default: "current_yaml"
	ProposedYamlFile   string                 `protobuf:"bytes,3,opt,name=proposed_yaml_file,json=proposedYamlFile,proto3" json:"proposed_yaml_file,omitempty"`
	CurrentYamlFile    string                 `protobuf:"bytes,4,opt,name=current_yaml_file,json=currentYamlFile,proto3" json:"current_yaml_file,omitempty"`
	Force              bool                   `protobuf:"varint,5,opt,name=force,proto3" json:"force,omitempty"`                                                       // emit diff even when content is identical
	IncludeIac         bool                   `protobuf:"varint,6,opt,name=include_iac,json=includeIac,proto3" json:"include_iac,omitempty"`                           // surface iac_relevant in output
	OutputToBlackboard bool                   `protobuf:"varint,7,opt,name=output_to_blackboard,json=outputToBlackboard,proto3" json:"output_to_blackboard,omitempty"` // post diff artifact to the Blackboard
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *SelfImproveDiffConfig) Reset() {
	*x = SelfImproveDiffConfig{}
	mi := &file_internal_contracts_orchestrator_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SelfImproveDiffConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SelfImproveDiffConfig) ProtoMessage() {}

func (x *SelfImproveDiffConfig) ProtoReflect() protoreflect.Message {
	mi := &file_internal_contracts_orchestrator_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SelfImproveDiffConfig.ProtoReflect.Descriptor instead.
func (*SelfImproveDiffConfig) Descriptor() ([]byte, []int) {
	return file_internal_contracts_orchestrator_proto_rawDescGZIP(), []int{7}
}

func (x *SelfImproveDiffConfig) GetProposedKey() string {
	if x != nil {
		return x.ProposedKey
	}
	return ""
}

func (x *SelfImproveDiffConfig) GetCurrentKey() string {
	if x != nil {
		return x.CurrentKey
	}
	return ""
}

func (x *SelfImproveDiffConfig) GetProposedYamlFile() string {
	if x != nil {
		return x.ProposedYamlFile
	}
	return ""
}

func (x *SelfImproveDiffConfig) GetCurrentYamlFile() string {
	if x != nil {
		return x.CurrentYamlFile
	}
	return ""
}

func (x *SelfImproveDiffConfig) GetForce() bool {
	if x != nil {
		return x.Force
	}
	return false
}

func (x *SelfImproveDiffConfig) GetIncludeIac() bool {
	if x != nil {
		return x.IncludeIac
	}
	return false
}

func (x *SelfImproveDiffConfig) GetOutputToBlackboard() bool {
	if x != nil {
		return x.OutputToBlackboard
	}
	return false
}

type SelfImproveDiffInput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProposedYaml  string                 `protobuf:"bytes,1,opt,name=proposed_yaml,json=proposedYaml,proto3" json:"proposed_yaml,omitempty"`
	CurrentYaml   string                 `protobuf:"bytes,2,opt,name=current_yaml,json=currentYaml,proto3" json:"current_yaml,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SelfImproveDiffInput) Reset() {
	*x = SelfImproveDiffInput{}
	mi := &file_internal_contracts_orchestrator_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SelfImproveDiffInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SelfImproveDiffInput) ProtoMessage() {}

func (x *SelfImproveDiffInput) ProtoReflect() protoreflect.Message {
	mi := &file_internal_contracts_orchestrator_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SelfImproveDiffInput.ProtoReflect.Descriptor instead.
func (*SelfImproveDiffInput) Descriptor() ([]byte, []int) {
	return file_internal_contracts_orchestrator_proto_rawDescGZIP(), []int{8}
}

func (x *SelfImproveDiffInput) GetProposedYaml() string {
	if x != nil {
		return x.ProposedYaml
	}
	return ""
}

func (x *SelfImproveDiffInput) GetCurrentYaml() string {
	if x != nil {
		return x.CurrentYaml
	}
	return ""
}

type SelfImproveDiffOutput struct {
	state        protoimpl.MessageState `protogen:"open.v1"`
	Diff         string                 `protobuf:"bytes,1,opt,name=diff,proto3" json:"diff,omitempty"`
	HasChanges   bool                   `protobuf:"varint,2,opt,name=has_changes,json=hasChanges,proto3" json:"has_changes,omitempty"`
	LinesAdded   int32                  `protobuf:"varint,3,opt,name=lines_added,json=linesAdded,proto3" json:"lines_added,omitempty"`
	LinesRemoved int32                  `protobuf:"varint,4,opt,name=lines_removed,json=linesRemoved,proto3" json:"lines_removed,omitempty"`
	IacRelevant  bool                   `protobuf:"varint,5,opt,name=iac_relevant,json=iacRelevant,proto3" json:"iac_relevant,omitempty"`
	// blackboard_warning is set when a Blackboard post is attempted but the
	// service is unavailable (non-fatal; the diff is still returned).
	BlackboardWarning string `protobuf:"bytes,100,opt,name=blackboard_warning,json=blackboardWarning,proto3" json:"blackboard_warning,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *SelfImproveDiffOutput) Reset() {
	*x = SelfImproveDiffOutput{}
	mi := &file_internal_contracts_orchestrator_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SelfImproveDiffOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SelfImproveDiffOutput) ProtoMessage() {}

func (x *SelfImproveDiffOutput) ProtoReflect() protoreflect.Message {
	mi := &file_internal_contracts_orchestrator_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SelfImproveDiffOutput.ProtoReflect.Descriptor instead.
func (*SelfImproveDiffOutput) Descriptor() ([]byte, []int) {
	return file_internal_contracts_orchestrator_proto_rawDescGZIP(), []int{9}
}

func (x *SelfImproveDiffOutput) GetDiff() string {
	if x != nil {
		return x.Diff
	}
	return ""
}

func (x *SelfImproveDiffOutput) GetHasChanges() bool {
	if x != nil {
		return x.HasChanges
	}
	return false
}

func (x *SelfImproveDiffOutput) GetLinesAdded() int32 {
	if x != nil {
		return x.LinesAdded
	}
	return 0
}

func (x *SelfImproveDiffOutput) GetLinesRemoved() int32 {
	if x != nil {
		return x.LinesRemoved
	}
	return 0
}

func (x *SelfImproveDiffOutput) GetIacRelevant() bool {
	if x != nil {
		return x.IacRelevant
	}
	return false
}

func (x *SelfImproveDiffOutput) GetBlackboardWarning() string {
	if x != nil {
		return x.BlackboardWarning
	}
	return ""
}

var File_internal_contracts_orchestrator_proto protoreflect.FileDescriptor

const file_internal_contracts_orchestrator_proto_rawDesc = "" +
	"\n" +
	"%internal/contracts/orchestrator.proto\x12 workflow.plugins.orchestrator.v1\"4\n" +
	"\x11LspDiagnoseConfig\x12\x1f\n" +
	"\vcontent_key\x18\x01 \x01(\tR\n" +
	"contentKey\"@\n" +
	"\x10LspDiagnoseInput\x12\x12\n" +
	"\x04yaml\x18\x01 \x01(\tR\x04yaml\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\"[\n" +
	"\rLspDiagnostic\x12\x1a\n" +
	"\bseverity\x18\x01 \x01(\tR\bseverity\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x14\n" +
	"\x05range\x18\x03 \x01(\tR\x05range\"\xb5\x01\n" +
	"\x11LspDiagnoseOutput\x12Q\n" +
	"\vdiagnostics\x18\x01 \x03(\v2/.workflow.plugins.orchestrator.v1.LspDiagnosticR\vdiagnostics\x12\x14\n" +
	"\x05count\x18\x02 \x01(\x05R\x05count\x12\x1d\n" +
	"\n" +
	"has_errors\x18\x03 \x01(\bR\thasErrors\x12\x18\n" +
	"\awarning\x18d \x01(\tR\awarning\"\x8d\x01\n" +
	"\x19SelfImproveValidateConfig\x12!\n" +
	"\fproposed_key\x18\x01 \x01(\tR\vproposedKey\x12\x1f\n" +
	"\vcurrent_key\x18\x02 \x01(\tR\n" +
	"currentKey\x12,\n" +
	"\x12proposed_yaml_file\x18\x03 \x01(\tR\x10proposedYamlFile\"b\n" +
	"\x18SelfImproveValidateInput\x12#\n" +
	"\rproposed_yaml\x18\x01 \x01(\tR\fproposedYaml\x12!\n" +
	"\fcurrent_yaml\x18\x02 \x01(\tR\vcurrentYaml\"e\n" +
	"\x19SelfImproveValidateOutput\x12\x14\n" +
	"\x05valid\x18\x01 \x01(\bR\x05valid\x12\x16\n" +
	"\x06errors\x18\x02 \x03(\tR\x06errors\x12\x1a\n" +
	"\bwarnings\x18\x03 \x03(\tR\bwarnings\"\x9e\x02\n" +
	"\x15SelfImproveDiffConfig\x12!\n" +
	"\fproposed_key\x18\x01 \x01(\tR\vproposedKey\x12\x1f\n" +
	"\vcurrent_key\x18\x02 \x01(\tR\n" +
	"currentKey\x12,\n" +
	"\x12proposed_yaml_file\x18\x03 \x01(\tR\x10proposedYamlFile\x12*\n" +
	"\x11current_yaml_file\x18\x04 \x01(\tR\x0fcurrentYamlFile\x12\x14\n" +
	"\x05force\x18\x05 \x01(\bR\x05force\x12\x1f\n" +
	"\vinclude_iac\x18\x06 \x01(\bR\n" +
	"includeIac\x120\n" +
	"\x14output_to_blackboard\x18\a \x01(\bR\x12outputToBlackboard\"^\n" +
	"\x14SelfImproveDiffInput\x12#\n" +
	"\rproposed_yaml\x18\x01 \x01(\tR\fproposedYaml\x12!\n" +
	"\fcurrent_yaml\x18\x02 \x01(\tR\vcurrentYaml\"\xe4\x01\n" +
	"\x15SelfImproveDiffOutput\x12\x12\n" +
	"\x04diff\x18\x01 \x01(\tR\x04diff\x12\x1f\n" +
	"\vhas_changes\x18\x02 \x01(\bR\n" +
	"hasChanges\x12\x1f\n" +
	"\vlines_added\x18\x03 \x01(\x05R\n" +
	"linesAdded\x12#\n" +
	"\rlines_removed\x18\x04 \x01(\x05R\flinesRemoved\x12!\n" +
	"\fiac_relevant\x18\x05 \x01(\bR\viacRelevant\x12-\n" +
	"\x12blackboard_warning\x18d \x01(\tR\x11blackboardWarningBKZIgithub.com/GoCodeAlone/workflow-plugin-agent/internal/contracts;contractsb\x06proto3"

var (
	file_internal_contracts_orchestrator_proto_rawDescOnce sync.Once
	file_internal_contracts_orchestrator_proto_rawDescData []byte
)

func file_internal_contracts_orchestrator_proto_rawDescGZIP() []byte {
	file_internal_contracts_orchestrator_proto_rawDescOnce.Do(func() {
		file_internal_contracts_orchestrator_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_contracts_orchestrator_proto_rawDesc), len(file_internal_contracts_orchestrator_proto_rawDesc)))
	})
	return file_internal_contracts_orchestrator_proto_rawDescData
}

var file_internal_contracts_orchestrator_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_internal_contracts_orchestrator_proto_goTypes = []any{
	(*LspDiagnoseConfig)(nil),         // 0: workflow.plugins.orchestrator.v1.LspDiagnoseConfig
	(*LspDiagnoseInput)(nil),          // 1: workflow.plugins.orchestrator.v1.LspDiagnoseInput
	(*LspDiagnostic)(nil),             // 2: workflow.plugins.orchestrator.v1.LspDiagnostic
	(*LspDiagnoseOutput)(nil),         // 3: workflow.plugins.orchestrator.v1.LspDiagnoseOutput
	(*SelfImproveValidateConfig)(nil), // 4: workflow.plugins.orchestrator.v1.SelfImproveValidateConfig
	(*SelfImproveValidateInput)(nil),  // 5: workflow.plugins.orchestrator.v1.SelfImproveValidateInput
	(*SelfImproveValidateOutput)(nil), // 6: workflow.plugins.orchestrator.v1.SelfImproveValidateOutput
	(*SelfImproveDiffConfig)(nil),     // 7: workflow.plugins.orchestrator.v1.SelfImproveDiffConfig
	(*SelfImproveDiffInput)(nil),      // 8: workflow.plugins.orchestrator.v1.SelfImproveDiffInput
	(*SelfImproveDiffOutput)(nil),     // 9: workflow.plugins.orchestrator.v1.SelfImproveDiffOutput
}
var file_internal_contracts_orchestrator_proto_depIdxs = []int32{
	2, // 0: workflow.plugins.orchestrator.v1.LspDiagnoseOutput.diagnostics:type_name -> workflow.plugins.orchestrator.v1.LspDiagnostic
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_internal_contracts_orchestrator_proto_init() }
func file_internal_contracts_orchestrator_proto_init() {
	if File_internal_contracts_orchestrator_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_contracts_orchestrator_proto_rawDesc), len(file_internal_contracts_orchestrator_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_internal_contracts_orchestrator_proto_goTypes,
		DependencyIndexes: file_internal_contracts_orchestrator_proto_depIdxs,
		MessageInfos:      file_internal_contracts_orchestrator_proto_msgTypes,
	}.Build()
	File_internal_contracts_orchestrator_proto = out.File
	file_internal_contracts_orchestrator_proto_goTypes = nil
	file_internal_contracts_orchestrator_proto_depIdxs = nil
}
